[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
evm_version = "cancun"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@uniswap/v2-core/=lib/v2-core/contracts/",
    "@uniswap/v2-periphery/=lib/v2-periphery/contracts/"
]

[lint]
exclude_lints = ["unaliased-plain-import", "screaming-snake-case-immutable", "unwrapped-modifier-logic", "asm-keccak256"]

